<?php
declare(strict_types=1);
namespace TeamDark\Panel;
final class Auth
{
private const RANK=['user'=>10,'reseller'=>20,'admin'=>30,'owner'=>40];
private const DUMMY_HASH='$argon2id$v=19$m=65536,t=4,p=1$SUxuLlU0OXJSVVFWM003Ug$Xit/khkKnxVa/NREpBST/GfoB+NQbwSfq+gdsQBEljU';
private static function passwordFingerprint(string $h):string{return hash('sha256',$h);}
public static function user():?array{Security::startSession();$id=(int)($_SESSION['uid']??0);if($id<=0)return null;$q=Database::pdo()->prepare('SELECT id,name,username,role,balance,telegram_chat_id,telegram_2fa_enabled,telegram_2fa_enabled_at,auth_version,login_not_before,status,password_hash,created_at FROM users WHERE id=? LIMIT 1');$q->execute([$id]);$u=$q->fetch();if(!$u||$u['status']!=='active'){Security::invalidateSession();return null;}$sf=(string)($_SESSION['auth_password_fingerprint']??'');$cf=self::passwordFingerprint((string)$u['password_hash']);$sv=(int)($_SESSION['auth_version']??0);$cv=max(1,(int)($u['auth_version']??1));if($sf===''||!hash_equals($cf,$sf)||$sv!==$cv){Security::invalidateSession();return null;}unset($u['password_hash']);return$u;}
public static function requireLogin():array{$u=self::user();if(!$u){header('Location: /login');exit;}return$u;}
public static function requireRole(array $u,string $min):void{if((self::RANK[$u['role']]??0)<(self::RANK[$min]??999)){http_response_code(403);throw new \RuntimeException('Forbidden.');}}
public static function canManageRole(array $a,string $target):bool{$ar=self::RANK[$a['role']]??0;$tr=self::RANK[$target]??999;return$a['role']==='owner'?$tr<40:$tr<$ar;}
public static function verifyPasswordCredentials(string $username,string $password,string $ratePrefix='web-login'):?array
{
$n=strtolower(trim($username));Security::rateLimit($ratePrefix,8,600);
if(strlen($n)>64||strlen($password)>200||str_contains($n,"\0"))return null;
$q=Database::pdo()->prepare('SELECT * FROM users WHERE username=? LIMIT 1');$q->execute([$n]);$u=$q->fetch();
$hash=$u?(string)$u['password_hash']:self::DUMMY_HASH;$passwordOk=password_verify($password,$hash);$ok=$u&&$u['status']==='active'&&$passwordOk;
if(!$ok){if($n!=='')Security::rateLimit($ratePrefix.'-account-fail',12,900,$n);Security::audit($u?(int)$u['id']:null,$ratePrefix==='api-login'?'api_login_failed':'login_failed',['username'=>substr($n,0,64)]);return null;}
if(!empty($u['login_not_before'])&&strtotime((string)$u['login_not_before'])>time()){Security::audit((int)$u['id'],'login_delayed',['not_before'=>$u['login_not_before']]);throw new \RuntimeException('Account activation delay is still active. Try again shortly.');}
if(password_needs_rehash((string)$u['password_hash'],defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_DEFAULT)){$new=Security::passwordHash($password);Database::pdo()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([$new,$u['id']]);$u['password_hash']=$new;}
if(PanelControl::blocked($u)){Security::audit((int)$u['id'],'login_maintenance_blocked');throw new \RuntimeException(PanelControl::settings()['message']);}
if($n!=='')Security::clearRateLimit($ratePrefix.'-account-fail',$n);Security::audit((int)$u['id'],'password_verified',['second_factor_required'=>(int)($u['telegram_2fa_enabled']??0)===1]);return$u;
}
public static function completeLogin(array $user):void{$id=(int)($user['id']??0);$q=Database::pdo()->prepare('SELECT id,name,username,role,balance,telegram_chat_id,telegram_2fa_enabled,telegram_2fa_enabled_at,auth_version,login_not_before,status,password_hash,created_at FROM users WHERE id=? LIMIT 1');$q->execute([$id]);$u=$q->fetch();if(!$u||$u['status']!=='active')throw new \RuntimeException('Account is unavailable.');if(PanelControl::blocked($u))throw new \RuntimeException(PanelControl::settings()['message']);Security::startSession();session_regenerate_id(true);unset($_SESSION['pending_2fa']);$n=time();$_SESSION['uid']=$id;$_SESSION['csrf']=bin2hex(random_bytes(32));$_SESSION['auth_password_fingerprint']=self::passwordFingerprint((string)$u['password_hash']);$_SESSION['auth_version']=max(1,(int)($u['auth_version']??1));$_SESSION['recent_auth_at']=$n;$_SESSION['session_started_at']=$n;$_SESSION['session_rotated_at']=$n;$_SESSION['last_activity']=$n;Database::pdo()->prepare('UPDATE users SET last_login_at=NOW(),last_login_ip=? WHERE id=?')->execute([Security::clientIp(),$id]);Security::audit($id,'login_success',['two_factor'=>(int)$u['telegram_2fa_enabled']===1]);}
public static function bumpAuthVersion(int $id,bool $revoke=true):int{if($id<=0)throw new \RuntimeException('Invalid user.');$pdo=Database::pdo();$pdo->beginTransaction();try{$pdo->prepare('UPDATE users SET auth_version=auth_version+1 WHERE id=?')->execute([$id]);if($revoke)$pdo->prepare('DELETE FROM api_tokens WHERE user_id=?')->execute([$id]);$q=$pdo->prepare('SELECT auth_version FROM users WHERE id=? LIMIT 1');$q->execute([$id]);$v=max(1,(int)$q->fetchColumn());$pdo->commit();return$v;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
public static function refreshCurrentSessionVersion(int $id,int $v):void{Security::startSession();if((int)($_SESSION['uid']??0)===$id){$_SESSION['auth_version']=max(1,$v);$_SESSION['recent_auth_at']=time();session_regenerate_id(true);}}
public static function markRecentAuth():void{Security::startSession();$_SESSION['recent_auth_at']=time();session_regenerate_id(true);}
public static function recentlyAuthenticated(int $seconds=300):bool{Security::startSession();$ts=(int)($_SESSION['recent_auth_at']??0);return$ts>0&&(time()-$ts)<=max(60,$seconds);}
public static function beginTwoFactorSession(array $c):void{$uid=(int)($c['user_id']??0);$cid=(int)($c['challenge_id']??0);$exp=(int)($c['expires_ts']??0);if($uid<=0||$cid<=0||$exp<=time())throw new \RuntimeException('Could not start two-factor authentication.');Security::startSession();session_regenerate_id(true);unset($_SESSION['uid'],$_SESSION['auth_password_fingerprint'],$_SESSION['auth_version'],$_SESSION['recent_auth_at']);$_SESSION['csrf']=bin2hex(random_bytes(32));$_SESSION['pending_2fa']=['user_id'=>$uid,'challenge_id'=>$cid,'expires_ts'=>$exp];$_SESSION['session_rotated_at']=time();$_SESSION['last_activity']=time();}
public static function pendingTwoFactor():?array{Security::startSession();$p=$_SESSION['pending_2fa']??null;if(!is_array($p)||(int)($p['user_id']??0)<=0||(int)($p['challenge_id']??0)<=0||(int)($p['expires_ts']??0)<=time()){unset($_SESSION['pending_2fa']);return null;}return$p;}
public static function clearPendingTwoFactor():void{Security::startSession();unset($_SESSION['pending_2fa']);}
public static function login(string $u,string $p):bool{$row=self::verifyPasswordCredentials($u,$p,'web-login');if(!$row)return false;if((int)($row['telegram_2fa_enabled']??0)===1)throw new \RuntimeException('Two-factor authentication required.');self::completeLogin($row);return true;}
public static function logout():void{try{$u=self::user();Security::audit($u?(int)$u['id']:null,'logout');}finally{Security::destroySession();}}
}
