<?php
declare(strict_types=1);
namespace TeamDark\Panel;
require_once __DIR__.'/PanelControl.php';
final class Security
{
public static function startSession():void{if(session_status()===PHP_SESSION_ACTIVE){self::touchSession();return;}session_name((string)Config::get('session_name'));session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>self::isHttps(),'httponly'=>true,'samesite'=>'Strict']);ini_set('session.use_strict_mode','1');ini_set('session.use_only_cookies','1');ini_set('session.use_trans_sid','0');session_start();self::touchSession();}
private static function touchSession():void{if(session_status()!==PHP_SESSION_ACTIVE)return;$n=time();$idle=max(300,(int)Config::get('session_idle_seconds',1800));$rot=max(300,(int)Config::get('session_rotate_seconds',900));$abs=max(1800,(int)Config::get('session_absolute_seconds',43200));$last=(int)($_SESSION['last_activity']??0);$start=(int)($_SESSION['session_started_at']??0);if(($last>0&&$n-$last>$idle)||($start>0&&$n-$start>$abs)){$_SESSION=[];session_regenerate_id(true);}$lr=(int)($_SESSION['session_rotated_at']??0);if(!$lr)$_SESSION['session_rotated_at']=$n;elseif($n-$lr>=$rot){session_regenerate_id(true);$_SESSION['session_rotated_at']=$n;}if(empty($_SESSION['session_started_at']))$_SESSION['session_started_at']=$n;$_SESSION['last_activity']=$n;}
public static function invalidateSession():void{self::startSession();$_SESSION=[];session_regenerate_id(true);$n=time();$_SESSION['session_started_at']=$n;$_SESSION['session_rotated_at']=$n;$_SESSION['last_activity']=$n;}
public static function destroySession():void{if(session_status()!==PHP_SESSION_ACTIVE)self::startSession();$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',['expires'=>time()-42000,'path'=>(string)($p['path']??'/'),'domain'=>(string)($p['domain']??''),'secure'=>(bool)($p['secure']??self::isHttps()),'httponly'=>true,'samesite'=>'Strict']);}session_destroy();}
public static function headers():void{header('Cache-Control: no-store, no-cache, must-revalidate, private, max-age=0');header('Pragma: no-cache');header('Expires: 0');header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: no-referrer');header('Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()');header('Cross-Origin-Opener-Policy: same-origin');header('Cross-Origin-Resource-Policy: same-origin');header('X-Permitted-Cross-Domain-Policies: none');header('X-Robots-Tag: noindex, nofollow, noarchive, nosnippet');header("Content-Security-Policy: default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'");if(self::isHttps())header('Strict-Transport-Security: max-age=31536000; includeSubDomains');}
public static function csrfToken():string{self::startSession();if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return(string)$_SESSION['csrf'];}
public static function verifyCsrf(?string $token):void{self::startSession();$known=(string)($_SESSION['csrf']??'');if($known===''||$token===null||!hash_equals($known,$token))throw new \RuntimeException('Invalid security token.');self::enforcePanelPolicy();}
private static function enforcePanelPolicy():void{if(strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'))!=='POST')return;$path=(string)(parse_url((string)($_SERVER['REQUEST_URI']??'/'),PHP_URL_PATH)?:'/');if($path==='/register'){$code=strtoupper(trim((string)($_POST['referral']??'')));if($code!==''){$q=Database::pdo()->prepare("SELECT i.role,u.role creator_role,u.status creator_status FROM referral_invites i JOIN users u ON u.id=i.created_by WHERE i.code=? AND i.status='pending' LIMIT 1");$q->execute([$code]);$r=$q->fetch();if($r){$allowed=$r['creator_role']==='owner'?['admin','reseller','user']:($r['creator_role']==='admin'?['user']:[]);if($r['creator_status']!=='active'||!in_array($r['role'],$allowed,true))throw new \RuntimeException('Referral is no longer authorized.');}}return;}$uid=(int)($_SESSION['uid']??0);if($uid<=0)return;$q=Database::pdo()->prepare('SELECT role,status FROM users WHERE id=? LIMIT 1');$q->execute([$uid]);$actor=$q->fetch();if(!$actor||$actor['status']!=='active')throw new \RuntimeException('Account is not active.');$priv=['/referrals/create','/referrals/revoke','/users/balance','/keys/action','/keys/devices/reset','/users/status','/users/role','/users/revoke-access','/users/password','/users/bulk','/users/2fa-reset','/users/telegram-reset','/telegram-users/key-action','/telegram/unlink','/telegram/link/start'];if(in_array($actor['role'],['owner','admin'],true)&&in_array($path,$priv,true)){$at=(int)($_SESSION['recent_auth_at']??0);if($at<=0||time()-$at>300)throw new \RuntimeException('Fresh sign-in required for this security action.');}if($actor['role']==='admin'&&$path==='/users/balance'){$delta=(int)($_POST['amount']??$_POST['delta']??0);if(abs($delta)>10000)throw new \RuntimeException('Admin balance adjustment exceeds the safety limit.');self::rateLimit('admin-balance-user',20,3600,(string)$uid);}}
public static function passwordHash(string $password):string{$a=defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_DEFAULT;return password_hash($password,$a);}
public static function clientIp():string{$r=trim((string)($_SERVER['REMOTE_ADDR']??''));if(filter_var($r,FILTER_VALIDATE_IP)===false)return'0.0.0.0';if(!self::trustedProxy($r))return$r;$cf=trim((string)($_SERVER['HTTP_CF_CONNECTING_IP']??''));if($cf!==''&&filter_var($cf,FILTER_VALIDATE_IP)!==false)return$cf;$xff=trim((string)($_SERVER['HTTP_X_FORWARDED_FOR']??''));if($xff!==''){$f=trim(explode(',',$xff,2)[0]);if(filter_var($f,FILTER_VALIDATE_IP)!==false)return$f;}return$r;}
private static function trustedProxy(string $r):bool{$raw=trim((string)Config::get('trusted_proxy_cidrs',''));if($raw==='')return false;foreach(preg_split('/\s*,\s*/',$raw)?:[]as$c){if($c!==''&&self::ipInCidr($r,$c))return true;}return false;}
private static function ipInCidr(string $ip,string $cidr):bool{if(!str_contains($cidr,'/'))return hash_equals($cidr,$ip);[$net,$pr]=explode('/',$cidr,2);$ib=@inet_pton($ip);$nb=@inet_pton(trim($net));if($ib===false||$nb===false||strlen($ib)!==strlen($nb))return false;$max=strlen($ib)*8;$p=filter_var($pr,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>$max]]);if($p===false)return false;$w=intdiv((int)$p,8);$rem=(int)$p%8;if($w>0&&substr($ib,0,$w)!==substr($nb,0,$w))return false;if($rem===0)return true;$mask=(0xFF<<(8-$rem))&0xFF;return(ord($ib[$w])&$mask)===(ord($nb[$w])&$mask);}
private static function rateLimitHash(string $bucket,?string $subject=null):string{if($subject===null&&preg_match('/^telegram-(?:bot|link)-(\d+)$/',$bucket,$m))$subject='telegram-chat:'.$m[1];$id=$subject===null?self::clientIp():trim($subject);return hash('sha256',$bucket.'|'.$id);}
public static function rateLimit(string $bucket,int $max,int $windowSeconds,?string $subject=null):void{$pdo=Database::pdo();$id=self::rateLimitHash($bucket,$subject);$max=max(1,$max);$start=time()-max(1,$windowSeconds);$pdo->beginTransaction();try{$pdo->prepare('INSERT IGNORE INTO rate_limits(bucket_hash,hits,touched_at) VALUES(?,0,NOW())')->execute([$id]);$q=$pdo->prepare('SELECT hits,UNIX_TIMESTAMP(touched_at) AS touched_ts FROM rate_limits WHERE bucket_hash=? FOR UPDATE');$q->execute([$id]);$row=$q->fetch();if(!$row)throw new \RuntimeException('Rate limit state unavailable.');if((int)$row['touched_ts']<$start)$pdo->prepare('UPDATE rate_limits SET hits=1,touched_at=NOW() WHERE bucket_hash=?')->execute([$id]);else{if((int)$row['hits']>=$max)throw new \RuntimeException('Too many requests. Try again later.');$pdo->prepare('UPDATE rate_limits SET hits=hits+1,touched_at=NOW() WHERE bucket_hash=?')->execute([$id]);}$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}try{if(random_int(1,100)===1)$pdo->prepare('DELETE FROM rate_limits WHERE touched_at < DATE_SUB(NOW(), INTERVAL 2 DAY) LIMIT 500')->execute();}catch(\Throwable){}}
public static function clearRateLimit(string $bucket,?string $subject=null):void{Database::pdo()->prepare('DELETE FROM rate_limits WHERE bucket_hash=?')->execute([self::rateLimitHash($bucket,$subject)]);}
public static function audit(?int $userId,string $action,array $meta=[]):void{try{$s=Database::pdo()->prepare('INSERT INTO audit_logs(user_id,action,ip_address,user_agent,meta_json) VALUES(?,?,?,?,?)');$s->execute([$userId,substr($action,0,100),self::clientIp(),substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255),json_encode($meta,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);if(random_int(1,500)===1)Database::pdo()->prepare('DELETE FROM audit_logs WHERE created_at < DATE_SUB(NOW(), INTERVAL 180 DAY) LIMIT 1000')->execute();}catch(\Throwable$e){error_log('TeamDark audit write failed: '.get_class($e));}}
private static function isHttps():bool{if(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')return true;$url=strtolower((string)Config::get('app_url',''));if(str_starts_with($url,'https://'))return true;$r=trim((string)($_SERVER['REMOTE_ADDR']??''));return self::trustedProxy($r)&&strtolower(trim((string)($_SERVER['HTTP_X_FORWARDED_PROTO']??'')))==='https';}
}
